helmDefaults:
  timeout: 600
  recreatePods: false
  tillerless: true

environments:
  default:
    values:
    - ./envs/default/values.yaml.gotmpl

repositories:
{{- range .Values }}
{{- if and (.enabled) (hasKey . "repository") }}
  - name: {{ .repository.name }}
    url: {{ .repository.url }}
{{- end }}
{{- end }}


releases:
  ## A special case where we want to load
{{- if or (.Values.certManager.enabled) (.Values.externalDNS.enabled) }}
  ## Mystique is a chart embedded in this repo that can be used to create
  ## general kubernetes resources such as secrets from files as shown here
  - name: cluster-system-extras
    namespace: cluster-system
    chart: ./charts/mystique
    values:
      - values/cluster-system/extras.yaml.gotmpl
{{- end }}

{{- if and (.Values.elasticsearch.enabled) (env "ELASTICSEARCH_PASSWORD") }}
  - name: elasticsearch-credentials
    namespace: {{ .Values.elasticsearch.namespace }}
    chart: ./charts/mystique
    values:
      - values/elasticsearch/credentials.yaml.gotmpl
{{- end }}

{{- if .Values.harbor.enabled }}
  - name: harbor-certs
    namespace: {{ .Values.harbor.namespace }}
    chart: ./charts/mystique
    values:
      - values/harbor/generated-certs.yaml
{{- end }}

{{- range .Values }}
{{- if .enabled }}
  - name: {{ .name }}
    namespace: {{ .namespace }}
    chart: {{ .chart }}
    version: "{{ .version }}"
    values:
      {{ .values | toYaml | indent 6 }}
{{- end }}
{{- end }}
