helmDefaults:
  timeout: 600
  recreatePods: false
{{- if not (env "HELMFILE_HELM3") }}
  tillerless: true
{{- end }}

environments:
  default:
    values:
    - values.yaml
    - {{ requiredEnv "ENV_DIR" }}/values.yaml.gotmpl


repositories:
{{- range .Values }}
{{- if and (.enabled) (hasKey . "repository") }}
  - name: {{ .repository.name }}
    url: {{ .repository.url }}
{{- end }}
{{- end }}

releases:
{{- range .Values }}
{{- if .enabled }}
{{- if hasKey . "raw" }}
  - name: {{ .name }}-raw
    namespace: {{ .namespace }}
    chart: ./charts/mystique
    values:
    {{- range .raw }}
      - {{ . }}
    {{- end }}
## If using helm3 make sure namespaces exist
{{- if env "HELMFILE_HELM3" }}
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "./scripts/create-namespace.sh"
        args: ["{{ .namespace }}"]
{{- end }}
{{- end }}
  - name: {{ .name }}
    namespace: {{ .namespace }}
    chart: {{ .chart }}
    version: "{{ . | getOrNil "version" }}"
    values:
    {{- range .values }}
      - {{ . }}
    {{- end }}
    secrets:
    {{- range . | getOrNil "secrets" }}
      - {{ . }}
    {{- end }}
## If using helm3 make sure namespaces exist
{{- if env "HELMFILE_HELM3" }}
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "./scripts/create-namespace.sh"
        args: ["{{ .namespace }}"]
      - events: ["cleanup"]
        command: "kubectl"
        args: ["delete", "ns", "{{ .namespace }}"]
{{- end }}
  {{- end }}
{{- end }}
