helmDefaults:
  timeout: 600
  recreatePods: false
  tillerless: true

environments:
  default:
    values:
    - values.yaml
    - {{ requiredEnv "ENV_DIR" }}/values.yaml.gotmpl

repositories:
{{- range .Values }}
{{- if and (.enabled) (hasKey . "repository") }}
  - name: {{ .repository.name }}
    url: {{ .repository.url }}
{{- end }}
{{- end }}

releases:
{{- range .Values }}
{{- if .enabled }}
{{- if hasKey . "raw" }}
  - name: {{ .name }}-raw
    namespace: {{ .namespace }}
    chart: ./charts/mystique
    values:
    {{- range .raw }}
      - {{ . }}
    {{- end }}
{{- end }}
  - name: {{ .name }}
    namespace: {{ .namespace }}
    chart: {{ .chart }}
    version: "{{ . | getOrNil "version" }}"
    values:
    {{- range .values }}
      - {{ . }}
    {{- end }}
    secrets:
    {{- range . | getOrNil "secrets" }}
      - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
