# Default values for gcp-lb-tags.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: paulczar/gcp-lb-tags
  tag: latest
  pullPolicy: Always

clusterUuid: cluster-id-from-pks-clusters
clusterName: cluster1

network: pks-network
region: us-central1
project: pgtm-pczarkowski

credentials: base64-encoded-google-json-creds-file

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
