apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gcp-lb-tags.fullname" . }}
  labels:
{{ include "gcp-lb-tags.labels" . | indent 4 }}
data:
  PROJECT: {{ .Values.project }}
  REGION: {{ .Values.region }}
  NAME: {{ .Values.clusterName }}
  GOOGLE_APPLICATION_CREDENTIALS: /google/credentials.json
  LABELS: deployment:service-instance-{{ .Values.clusterUuid }},job:master
  NETWORK: {{ .Values.network }}
  TAGS: service-instance-{{ .Values.clusterUuid }}-master
