apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gcp-lb-tags.fullname" . }}
  labels:
{{ include "gcp-lb-tags.labels" . | indent 4 }}
data:
  credentials.json: {{ .Values.credentials | quote }}
